use javaproject;
CREATE TABLE users(id INT PRIMARY KEY  AUTO_INCREMENT,
firstname VARCHAR(100) NOT NULL,
lastname VARCHAR(100) NOT NULL,
username VARCHAR(50)  NOT NULL,
password VARCHAR(50) NOT NULL,
phone_number VARCHAR(20)  UNIQUE NOT NULL,
email VARCHAR(50) NOT NULL,
dob DATE NOT NULL,
user_type ENUM('CUSTOMER','DRIVER') NOT NULL,
gender VARCHAR(10) NOT NULL,
address VARCHAR(100) NOT NULL);

SELECT *FROM users;
 

CREATE TABLE bookings(
booking_id INT PRIMARY KEY AUTO_INCREMENT,
id int,
source VARCHAR(500) NOT NULL,
destination VARCHAR(500) NOT NULL,
 booking_date DATE NOT NULL,
 booking_time TIME NOT NULL,
status ENUM('PENDING','CONFIRMED','COMPLETED','CANCELLED') default 'PENDING',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
               ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (id) REFERENCES users(id)
);

SELECT*FROM bookings;


